steps:
  - name: "gcr.io/code-zero-zem/builder"
    entrypoint: 'gradle'
    dir: './components/model-dependent'
    args: ["build"]
  - name: "gcr.io/code-zero-zem/builder"
    entrypoint: "npm"
    dir: './tools/quicktype/src'
    args: ["run", "lint"]
